# Generated by Django 6.0.4 on 2026-05-01 19:19

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'About section',
                'verbose_name_plural': 'About section',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('slug', models.SlugField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('title_en', models.CharField(max_length=512)),
                ('title_ne', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=32)),
                ('updated', models.DateField()),
                ('premium', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title_en'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TaxLexis', max_length=255)),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13'), max_digits=6)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_signups', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=512)),
                ('og_image', models.URLField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('ga_id', models.CharField(blank=True, max_length=64)),
                ('robots_txt', models.TextField(blank=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_pass', models.CharField(blank=True, max_length=255)),
                ('email_from_name', models.CharField(blank=True, max_length=255)),
                ('esewa_enabled', models.BooleanField(default=False)),
                ('esewa_secret_key', models.CharField(blank=True, max_length=255)),
                ('esewa_product_code', models.CharField(blank=True, max_length=128)),
                ('esewa_live', models.BooleanField(default=False)),
                ('khalti_enabled', models.BooleanField(default=False)),
                ('khalti_live_key', models.CharField(blank=True, max_length=255)),
                ('khalti_test_key', models.CharField(blank=True, max_length=255)),
                ('khalti_live', models.BooleanField(default=False)),
                ('nav_order', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], max_length=16)),
                ('pan_vat', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('joined_at', models.DateField()),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='ContentTypeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Content type',
                'verbose_name_plural': 'Content types',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=512)),
                ('copyright', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Footer config',
                'verbose_name_plural': 'Footer config',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('cta', models.CharField(max_length=128)),
                ('href', models.CharField(max_length=512)),
                ('image', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('reference_number', models.CharField(max_length=128)),
                ('date_filed', models.DateField()),
                ('date_decided', models.DateField(blank=True, null=True)),
                ('court', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('practice_area', models.SlugField()),
                ('teaser', models.TextField(blank=True)),
                ('parties', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('full_content', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Legal case',
                'verbose_name_plural': 'Legal cases',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('image', models.URLField(max_length=500)),
                ('date', models.DateField()),
                ('href', models.CharField(max_length=512)),
                ('tag', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PermissionModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('features', models.JSONField(default=list)),
                ('cta', models.CharField(max_length=128)),
                ('highlight', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('steps_count', models.PositiveSmallIntegerField(default=0)),
                ('duration_label', models.CharField(blank=True, max_length=128)),
                ('icon', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('href', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteHomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_hero', models.BooleanField(default=True)),
                ('section_about', models.BooleanField(default=True)),
                ('section_services', models.BooleanField(default=True)),
                ('section_team', models.BooleanField(default=True)),
                ('section_news', models.BooleanField(default=True)),
                ('section_footer', models.BooleanField(default=True)),
                ('section_procedures', models.BooleanField(default=True)),
                ('section_styles', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Site homepage config',
                'verbose_name_plural': 'Site homepage config',
            },
        ),
        migrations.CreateModel(
            name='SiteNavItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=128)),
                ('href', models.CharField(max_length=512)),
                ('is_dropdown', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SummaryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('editor', 'Editor'), ('client', 'Client'), ('user', 'User')], default='user', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=16)),
                ('subscribed', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=32)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.aboutsection')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('excerpt', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('author_name', models.CharField(blank=True, help_text='Cached display name when author FK is empty.', max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.contenttypemodel')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.footerconfig')),
            ],
            options={
                'ordering': ['config', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=512)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footercolumn')),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('href', models.URLField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.footerconfig')),
            ],
            options={
                'ordering': ['config', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.procedure')),
            ],
            options={
                'ordering': ['procedure', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In progress'), ('review', 'Review'), ('completed', 'Completed')], default='planning', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client')),
                ('team', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteNavChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('href', models.CharField(max_length=512)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.sitenavitem')),
            ],
            options={
                'ordering': ['parent', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('posted', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('preview', models.TextField(blank=True)),
                ('premium', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='core.summarycategory')),
            ],
            options={
                'verbose_name_plural': 'Summaries',
                'ordering': ['-posted'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NPR', 'NPR'), ('USD', 'USD')], default='NPR', max_length=8)),
                ('method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank'), ('stripe', 'Stripe')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('txn_code', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=16)),
                ('pan', models.CharField(blank=True, max_length=64)),
                ('vat', models.CharField(blank=True, max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permissionmodule')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role')),
            ],
            options={
                'verbose_name': 'Role permission',
                'verbose_name_plural': 'Role permissions',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
