# Generated by Django 6.0.4 on 2026-05-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], help_text='Subscription tier granted when this payment is verified.', max_length=32),
        ),
    ]
