# Generated by Django 6.0.4 on 2026-05-02 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_plan_and_logic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('role_title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('image', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Testimonials section',
                'verbose_name_plural': 'Testimonials section',
            },
        ),
        migrations.AddField(
            model_name='heroslide',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_cta',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_href',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='sitehomepageconfig',
            name='section_testimonials',
            field=models.BooleanField(default=True),
        ),
    ]
