# Generated by Django 6.0.4 on 2026-05-02 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonials_and_hero_eyebrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_digits', models.CharField(db_index=True, max_length=16)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP verification',
                'verbose_name_plural': 'OTP verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
