# Generated by Django 6.0.4 on 2026-05-02 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimonialsconfig_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help article',
                'verbose_name_plural': 'Help articles',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='testimonialsconfig',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
