# Generated by Django 6.0.4 on 2026-05-03 08:53

import core.models
from django.db import migrations, models


def _clear_external_image_strings(apps, schema_editor):
    """Drop stored http(s) / protocol-relative URLs so ImageField paths are not poisoned by legacy strings."""
    User = apps.get_model("core", "User")
    AppSettings = apps.get_model("core", "AppSettings")
    HeroSlide = apps.get_model("core", "HeroSlide")
    AboutSection = apps.get_model("core", "AboutSection")
    TeamMember = apps.get_model("core", "TeamMember")
    NewsItem = apps.get_model("core", "NewsItem")
    Testimonial = apps.get_model("core", "Testimonial")

    def is_remote(s):
        if not s or not isinstance(s, str):
            return False
        t = s.strip()
        return t.startswith("http://") or t.startswith("https://") or t.startswith("//") or t.startswith("data:")

    for u in User.objects.iterator():
        av = getattr(u, "avatar", None) or ""
        if av and is_remote(str(av)):
            User.objects.filter(pk=u.pk).update(avatar=None)
    s = AppSettings.objects.first()
    if s and is_remote(s.og_image or ""):
        AppSettings.objects.filter(pk=s.pk).update(og_image="")
    for row in HeroSlide.objects.exclude(image="").iterator():
        if is_remote(row.image or ""):
            HeroSlide.objects.filter(pk=row.pk).update(image="")
    a = AboutSection.objects.first()
    if a and is_remote(a.image or ""):
        AboutSection.objects.filter(pk=a.pk).update(image="")
    for row in TeamMember.objects.exclude(avatar="").iterator():
        if is_remote(row.avatar or ""):
            TeamMember.objects.filter(pk=row.pk).update(avatar="")
    for row in NewsItem.objects.exclude(image="").iterator():
        if is_remote(row.image or ""):
            NewsItem.objects.filter(pk=row.pk).update(image="")
    for row in Testimonial.objects.exclude(image="").iterator():
        if is_remote(row.image or ""):
            Testimonial.objects.filter(pk=row.pk).update(image="")


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactmessage'),
    ]

    operations = [
        migrations.RunPython(_clear_external_image_strings, _noop_reverse),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models._upload_cms_about),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='og_image',
            field=models.ImageField(blank=True, upload_to=core.models._upload_app_og_image),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models._upload_cms_hero),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models._upload_cms_news),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.models._upload_cms_team_avatar),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models._upload_cms_testimonial),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._upload_user_avatar),
        ),
    ]
