# Generated by Django 6.0.4 on 2026-05-03 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_entitlements_and_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='Scale', max_length=64)),
                ('overview', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('related_cases_title', models.CharField(blank=True, max_length=255)),
                ('services', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Practice areas',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
