# Generated by Django — seed PracticeArea rows when table is empty.

from django.db import migrations

from core.practice_area_default_seed import default_practice_area_rows


def forwards(apps, schema_editor):
    PracticeArea = apps.get_model("core", "PracticeArea")
    if PracticeArea.objects.exists():
        return
    for row in default_practice_area_rows():
        PracticeArea.objects.create(**row)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_practice_area"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
