# Generated by Django 6.0.4 on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_practice_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billing_cycle',
            field=models.CharField(
                choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')],
                default='monthly',
                help_text='Billing period for the purchased package (drives subscription length when verified).',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rejection_reason',
            field=models.TextField(
                blank=True,
                help_text='When rejected by Super Admin, reason text (also sent to the client by SMS).',
            ),
        ),
    ]
