# Generated by Django 6.0.4 on 2026-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_subscription_period_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Choose Your Plan', max_length=255)),
                ('page_subtitle', models.TextField(default="Unlock Nepal's full legal & tax knowledge base. Cancel anytime.")),
                ('faq_section_title', models.CharField(default='Frequently Asked Questions', max_length=255)),
                ('popular_badge_label', models.CharField(default='Most Popular', max_length=128)),
                ('faq_category', models.CharField(default='Pricing', help_text='Published help articles whose category matches this value exactly are shown as FAQs.', max_length=128)),
            ],
            options={
                'verbose_name': 'Pricing page',
                'verbose_name_plural': 'Pricing page',
            },
        ),
    ]
