# Generated by Django 6.0.4 on 2026-05-03 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_pricing_help_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryAudienceVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_key', models.CharField(blank=True, max_length=64, null=True)),
                ('vote', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=8)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_votes', to='core.summary')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('summary', 'user'), name='uniq_summary_audience_vote_user'), models.UniqueConstraint(condition=models.Q(('visitor_key__isnull', False)), fields=('summary', 'visitor_key'), name='uniq_summary_audience_vote_visitor')],
            },
        ),
        migrations.CreateModel(
            name='SummaryDailyViewerView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_key', models.CharField(db_index=True, max_length=96)),
                ('day', models.DateField(db_index=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_viewer_views', to='core.summary')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('summary', 'actor_key', 'day'), name='uniq_summary_daily_view_actor')],
            },
        ),
    ]
