# Generated by Django 6.0.4 on 2026-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appsettings_payments_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='payments_enabled',
            field=models.BooleanField(default=False, help_text='When on, users may submit subscription payments from the dashboard Wallet tab only.'),
        ),
    ]
