# Generated by Django — package expiry notification dedupe

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_professionals_page_config_team_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_notified_plan_benefits_end",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="plan_benefits_end value for which we already sent package-ended email/SMS/in-app notice.",
            ),
        ),
    ]
