# Generated by Django 6.0.4 on 2026-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_act_detail_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_notified_plan_benefits_end',
            field=models.DateTimeField(blank=True, help_text='When plan_benefits_end passed, we notify once per ended period; this stores that end datetime.', null=True),
        ),
    ]
