# Generated by Django 5.x

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_user_last_notified_plan_benefits_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="site_logo",
            field=models.ImageField(blank=True, upload_to=core.models._upload_app_site_logo),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="site_favicon",
            field=models.FileField(blank=True, upload_to=core.models._upload_app_site_favicon),
        ),
    ]
