# Generated by Django — links core.User.role to core.Role

from django.db import migrations, models
import django.db.models.deletion


def forwards_assign_role_fk(apps, schema_editor):
    User = apps.get_model("core", "User")
    Role = apps.get_model("core", "Role")
    known = ("super_admin", "admin", "editor", "client", "user")
    role_pk_by_key: dict[str, object] = {}
    for k in known:
        ro, _ = Role.objects.get_or_create(
            key=k,
            defaults={
                "name": k.replace("_", " ").title(),
                "description": "",
                "is_system": True,
            },
        )
        role_pk_by_key[k] = ro.pk
    fallback = role_pk_by_key["user"]
    for u in User.objects.all():
        raw = getattr(u, "role", None)
        key = (raw or "user").strip() if isinstance(raw, str) else "user"
        rid = role_pk_by_key.get(key) or fallback
        User.objects.filter(pk=u.pk).update(role_tmp_id=rid)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_act_legalcase_procedure_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_tmp",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.role",
            ),
        ),
        migrations.RunPython(forwards_assign_role_fk, noop_reverse),
        migrations.RemoveField(model_name="user", name="role"),
        migrations.RenameField(model_name="user", old_name="role_tmp", new_name="role"),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.role",
            ),
        ),
    ]
