# Generated by Django 6.0.4 on 2026-05-06 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_role_fk_to_role_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('issued_by', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['sort_order', '-created_at', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['category__sort_order', 'category__name', 'title']},
        ),
        migrations.CreateModel(
            name='NoticeDailyViewerView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_key', models.CharField(db_index=True, max_length=96)),
                ('day', models.DateField(db_index=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_viewer_views', to='core.notice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notice', 'actor_key', 'day'), name='uniq_notice_daily_view_actor')],
            },
        ),
    ]
