# Generated by Django 5.x — widen testimonial sort order for large CMS lists.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_knowledgeresourcecategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
