# Generated by Django 6.0.4 on 2026-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_emailtemplate_automate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Admin hint: when this email is sent and which placeholders are available.'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
