# Generated by Django 6.0.4 on 2026-05-18 20:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_seo_entity_meta_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='meta_og_image',
            field=models.ImageField(blank=True, help_text='Social share image for this item. Falls back to site Settings → SEO default OG image.', upload_to=core.models._upload_entity_meta_og_image),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_og_image',
            field=models.ImageField(blank=True, help_text='Social share image for this item. Falls back to site Settings → SEO default OG image.', upload_to=core.models._upload_entity_meta_og_image),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='meta_og_image',
            field=models.ImageField(blank=True, help_text='Social share image for this item. Falls back to site Settings → SEO default OG image.', upload_to=core.models._upload_entity_meta_og_image),
        ),
        migrations.AddField(
            model_name='notice',
            name='meta_og_image',
            field=models.ImageField(blank=True, help_text='Social share image for this item. Falls back to site Settings → SEO default OG image.', upload_to=core.models._upload_entity_meta_og_image),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='meta_og_image',
            field=models.ImageField(blank=True, help_text='Social share image for this item. Falls back to site Settings → SEO default OG image.', upload_to=core.models._upload_entity_meta_og_image),
        ),
        migrations.AddField(
            model_name='procedure',
            name='meta_og_image',
            field=models.ImageField(blank=True, help_text='Social share image for this item. Falls back to site Settings → SEO default OG image.', upload_to=core.models._upload_entity_meta_og_image),
        ),
        migrations.AddField(
            model_name='summary',
            name='meta_og_image',
            field=models.ImageField(blank=True, help_text='Social share image for this item. Falls back to site Settings → SEO default OG image.', upload_to=core.models._upload_entity_meta_og_image),
        ),
    ]
