"""Staff-only admin API routes."""

from django.urls import path

from core.views.admin import dashboard_views, x_views

urlpatterns = [
    path("dashboard/summary/", dashboard_views.admin_dashboard_summary),
    path("dashboard/analytics/", dashboard_views.admin_dashboard_analytics),
    path("users/", x_views.admin_users),
    path("users/<int:user_id>/impersonate/", x_views.admin_user_impersonate),
    path("users/<int:user_id>/revoke-subscription/", x_views.admin_user_revoke_subscription),
    path("users/<int:user_id>/", x_views.admin_user_detail),
    path("permission-modules/", x_views.admin_permission_modules),
    path("permission-modules/<uuid:module_id>/", x_views.admin_permission_module_detail),
    path("roles/", x_views.admin_roles),
    path("roles/<uuid:role_id>/", x_views.admin_role_detail),
    path("role-permissions/", x_views.admin_role_permissions),
    path("role-permissions/<uuid:rp_id>/", x_views.admin_role_permission_detail),
    path("transactions/", x_views.admin_transactions),
    path("transactions/<uuid:txn_id>/", x_views.admin_transaction_detail),
    path("clients/", x_views.admin_clients),
    path("clients/<uuid:client_id>/", x_views.admin_client_detail),
    path("projects/", x_views.admin_projects),
    path("projects/<uuid:project_id>/", x_views.admin_project_detail),
    path("pricing-plans/", x_views.admin_pricing_plans),
    path("pricing-plans/<uuid:plan_id>/", x_views.admin_pricing_plan_detail),
    path("settings/test-mail/", x_views.admin_app_settings_test_mail),
    path("settings/", x_views.admin_app_settings),
    path("blog-posts/", x_views.admin_blog_posts),
    path("blog-posts/<uuid:post_id>/", x_views.admin_blog_post_detail),
    path("cms/hero-slides/", x_views.admin_hero_slides),
    path("cms/hero-slides/<uuid:slide_id>/", x_views.admin_hero_slide_detail),
    path("cms/nav-items/", x_views.admin_nav_items),
    path("cms/nav-items/<uuid:nav_id>/", x_views.admin_nav_item_detail),
    path("cms/homepage/", x_views.admin_cms_homepage_snapshot),
    path("help-articles/", x_views.admin_help_articles),
    path("help-articles/<uuid:article_id>/", x_views.admin_help_article_detail),
    path("contact-messages/", x_views.admin_contact_messages),
    path("contact-messages/<uuid:message_id>/", x_views.admin_contact_message_detail),
    path("panel-notifications/mark-all-read/", x_views.admin_panel_notifications_mark_all_read),
    path("panel-notifications/<uuid:notification_id>/", x_views.admin_panel_notification_detail),
    path("panel-notifications/", x_views.admin_panel_notifications),
    path("practice-areas/", x_views.admin_practice_areas),
    path("practice-areas/<uuid:area_id>/", x_views.admin_practice_area_detail),
    path("legal-cases/", x_views.admin_legal_cases),
    path("legal-cases/<uuid:case_id>/", x_views.admin_legal_case_detail),
    path("act-categories/", x_views.admin_act_categories),
    path("act-categories/<uuid:category_id>/", x_views.admin_act_category_detail),
    path("legal-case-categories/", x_views.admin_legal_case_categories),
    path("legal-case-categories/<uuid:category_id>/", x_views.admin_legal_case_category_detail),
    path("procedure-categories/", x_views.admin_procedure_categories),
    path("procedure-categories/<uuid:category_id>/", x_views.admin_procedure_category_detail),
    path("summary-categories/", x_views.admin_summary_categories),
    path("summary-categories/<uuid:category_id>/", x_views.admin_summary_category_detail),
    path("summaries/", x_views.admin_summaries),
    path("summaries/<uuid:summary_id>/", x_views.admin_summary_detail),
    path("acts/", x_views.admin_acts),
    path("acts/<slug:slug>/", x_views.admin_act_detail),
    path("procedures/", x_views.admin_procedures),
    path("procedures/<uuid:procedure_id>/", x_views.admin_procedure_detail),
    path("notices/", x_views.admin_notices),
    path("notices/<uuid:notice_id>/", x_views.admin_notice_detail),
    path("knowledge-resource-categories/", x_views.admin_knowledge_resource_categories),
    path("knowledge-resource-categories/<uuid:category_id>/", x_views.admin_knowledge_resource_category_detail),
    path("knowledge-resources/", x_views.admin_knowledge_resources),
    path(
        "knowledge-resources/<uuid:resource_id>/preview-pdf/",
        x_views.admin_knowledge_resource_pdf_preview,
    ),
    path("knowledge-resources/<uuid:resource_id>/", x_views.admin_knowledge_resource_detail),
]
