"""Public and client-facing API routes."""

from django.urls import path

from core.views.client import esewa_views, home_views, seo_views

urlpatterns = [
    # SEO guide routes (Appendix A) + legacy aliases
    path("meta/sitemap.xml", seo_views.public_sitemap_xml),
    path("public/sitemap.xml", seo_views.public_sitemap_xml),
    path("public/robots.txt", seo_views.public_robots_txt),
    path("public/page-meta/", seo_views.public_page_meta),
    path("public/share-preview/", seo_views.public_share_preview),
    path("blog-posts/<uuid:post_id>/share/", seo_views.blog_post_share),
    path("summaries/<slug:slug>/share/", seo_views.summary_share),
    path("notices/<slug:slug>/share/", seo_views.notice_share),
    path("acts/<slug:slug>/share/", seo_views.act_share),
    path("settings/public/", home_views.public_config),
    path("public/config/", home_views.public_config),
    path("public/translate/en-ne/", home_views.public_translate_en_ne),
    path("public/contact/", home_views.public_contact_submit),
    path("public/help-articles/", home_views.public_help_articles_list),
    path("public/notices/track-views/", home_views.public_notices_track_views),
    path("public/notices/legacy/<uuid:notice_id>/", home_views.public_notice_legacy_slug),
    path("public/notices/<slug:slug>/vote/", home_views.public_notice_vote),
    path("public/notices/<slug:slug>/", home_views.public_notice_detail),
    path("public/notices/", home_views.public_notices_list),
    path("public/knowledge-resource-categories/", home_views.public_knowledge_resource_categories_list),
    path("public/knowledge-resources/", home_views.public_knowledge_resources_list),
    path("public/knowledge-resources/track-downloads/", home_views.public_knowledge_resources_track_downloads),
    path(
        "public/knowledge-resources/<uuid:resource_id>/download/",
        home_views.public_knowledge_resource_download,
    ),
    path("site/homepage/", home_views.site_homepage),
    path("public/professionals/", home_views.public_professionals_page),
    path("acts/", home_views.acts_list),
    path("acts/<slug:slug>/", home_views.act_detail),
    path("summary-categories/", home_views.summary_categories_list),
    path("summaries/track-views/", home_views.summary_track_views),
    path("summaries/<slug:slug>/vote/", home_views.summary_vote),
    path("summaries/", home_views.summaries_list),
    path("summaries/<slug:slug>/", home_views.summary_detail),
    path("practice-areas/", home_views.practice_areas_list),
    path("legal-cases/", home_views.legal_cases_list),
    path("legal-cases/<slug:slug>/", home_views.legal_case_detail),
    path("procedures/", home_views.procedures_list),
    path("procedures/<slug:slug>/", home_views.procedure_detail),
    path("pricing-plans/", home_views.pricing_plans_list),
    path("pricing-page/", home_views.pricing_page),
    path("blog-posts/", home_views.blog_posts_list),
    path("blog-posts/<uuid:post_id>/", home_views.blog_post_detail),
    path("auth/signup/", home_views.auth_signup),
    path("auth/login/", home_views.auth_login),
    path("auth/google/", home_views.auth_google),
    path("auth/otp/request/", home_views.auth_otp_request),
    path("auth/otp/verify/", home_views.auth_otp_verify),
    path("auth/password-reset/request/", home_views.auth_password_reset_request),
    path("auth/password-reset/confirm/", home_views.auth_password_reset_confirm),
    path("auth/logout/", home_views.auth_logout),
    path("auth/stop-impersonate/", home_views.auth_stop_impersonate),
    path("auth/me/", home_views.auth_me),
    path("auth/help-articles/", home_views.auth_help_articles),
    path("auth/dashboard/", home_views.auth_dashboard),
    path("auth/my-contact-messages/", home_views.auth_my_contact_messages),
    path("auth/my-projects/", home_views.auth_my_projects),
    path("auth/notifications/<uuid:notification_id>/read/", home_views.auth_notification_mark_read),
    path("subscriptions/pending/", home_views.subscriptions_pending),
    path("payments/esewa/initiate/", esewa_views.esewa_payment_initiate),
    path("payments/esewa/success/", esewa_views.esewa_payment_success),
    path("payments/esewa/failure/", esewa_views.esewa_payment_failure),
]
